%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: \\wsl.localhost\ubuntu-22.04\home\alixa\Al-project\baseline-dualFibre-nonIdealAdded\GrainSize0.txt
%
% Auto-generated by MATLAB on 20-Jul-2023 11:16:11

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
GrainSize0 = readtable("GrainSize0.txt", opts);

%% Convert to output type
GrainSize0 = table2array(GrainSize0);

%% Clear temporary variables
clear opts