%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\alixa\Documents\myPROJECTS\Aluminium\addingNoisetoOrientationGeneration\ODFCalcMethod\LargerDomain\GrainSize.txt
%
% Auto-generated by MATLAB on 21-Jul-2023 17:59:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
GrainSize = readtable("GrainSize.txt", opts);
GrainSize = table2array(GrainSize);


%% Clear temporary variables
clear opts