%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/alikhajezade/Desktop/ODFCalcMethod-EDPlane/mode.txt
%
% Auto-generated by MATLAB on 26-Dec-2020 21:52:48

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
mode = readtable("mode4.txt", opts);

%% Convert to output type
mode = table2array(mode);

%% Clear temporary variables
clear opts